yalesites-org/atomic

- templates/paragraphs/paragraph--image.html.twig
- templates/paragraphs/paragraph--pop-out-image.html.twig
- Adds functionality bullet item
- Fixes this or that bullet item
> chore(YALB-476) fix image aria-labels

- CONTRIBUTING.md
- README.md
- Documents contributing to the theme, including how we use semver for automated releases
> YALB-480: Setup semver on theme repo

- templates/paragraphs/paragraph--accordion.html.twig
- Added dot notation to only show accordion heading if it is present
> YALB-540: Accordion heading

- package-lock.json
- templates/node/node--event--full.html.twig
- Creates a Drupal template for the Event full display mode
> YALB-494: Wire Event Page

- atomic.theme
- templates/node/node--news--card.html.twig
- templates/node/node--news--list-item.html.twig
- templates/paragraphs/paragraph--news-cards.html.twig
- templates/paragraphs/paragraph--news-list.html.twig
> YALB-491: Wire news cards and views

- atomic.libraries.yml
- Adds the `core/drupal` dependency so that all of our JS will work
> YALB-564: Anonymous JS

- package-lock.json
- templates/layout/region--footer.html.twig
- templates/ys/ys-social-links.html.twig
- Adds social links block to footer region
> YALB 634 wire footer

- atomic.libraries.yml
- package-lock.json
- templates/field/field--paragraph--field-tab.html.twig
- templates/paragraphs/paragraph--tab.html.twig
- templates/paragraphs/paragraph--tabs.html.twig
> YALB-106: wire tabs

- atomic.libraries.yml
- Adds functionality bullet item
- Fixes this or that bullet item
> fix(YALB-639): update drupal libraries to use the new namespaces

- templates/paragraphs/paragraph--quick-links.html.twig
- Wires the quick-links subtle variation to drupal.
> YALB-94: shows subtle variation in drupal

- components/_settings/_config.css
- package-lock.json
- templates/paragraphs/paragraph--quick-links.html.twig
- Replaces old config properties with new ones, and leaves them all commented out by default.
> YALB-598: Global Settings

- atomic.info.yml
- templates/paragraphs/paragraph--cta-banner.html.twig
- Fixes action banner wiring
- Implements lpb css
> YALB-742: Update action banner

- templates/navigation/menu-local-task.html.twig
- templates/navigation/menu-local-tasks.html.twig
- Styles local tasks (Edit, Delete, etc.) like the tabs component
> YALB-273: Style local tasks

- templates/paragraphs/paragraph--callout-item.html.twig
- fix: content field mapping to [0] as logic check
> YALB-795: Callout edits in Drupal

- .gitignore
- package-lock.json
- Adds functionality bullet item
- Fixes this or that bullet item
> Yalb 823 type changes

- templates/paragraphs/paragraph--embed.html.twig
- Replaces the legacy 'embed' paragraph template with a generic {{ content }} render.
No functional changes. This is removing any custom logic so that we can theme the new embed codes in a future PR.
> YALB-828: Embeds

- templates/paragraphs/paragraph--event-cards.html.twig
- templates/paragraphs/paragraph--news-cards.html.twig
… cards
- Removes unused paragraph templates for news cards and event cards
> YALB-934: Views: Replace existing list/card paragraphs

- package-lock.json
> Release (hotfix)

- atomic.theme
- Adds `is_active` twig variable to menu item of current page only, not parents.
> YABL-933: Menu: Active trail styles

- components/_settings/_config.css
- Update styles to fix position of items when hover on local task
- I added styles here because I couldn't do it in other way, please let me know if it has to be in another way :)
> YALB-1012: Admin Theme: Local Tasks style

- templates/block/layout-builder/block--inline-block--divider.html.twig
- Adds the passing of new dial variables to the component library
> YALB-1137: Dividers add new dials to divider block

- css/admin-theme.css
- Prevents adding more media items to a limited media item field
- Requires [PR-327](https://github.com/yalesites-org/yalesites-project/pull/327)
> YALB-1318: Bug: media library - gallery block - multiple photos error

- templates/layout/region--header.html.twig
- templates/navigation/menu--extras--main.html.twig
- Wiring PR for YALB-1574
- All testing notes are in main [PR-469](https://github.com/yalesites-org/yalesites-project/pull/469)
> YALB-1574: Branding: Header Variations Backend

- templates/block/layout-builder/block--inline-block--callout.html.twig
> YALB-1644 - Dial: Center-align callout with content-width content - wiring

- atomic.libraries.yml
- templates/field/field--node--title.html.twig
- templates/node/node--event--card.html.twig
- templates/node/node--event--condensed.html.twig
- templates/node/node--event--list-item.html.twig
- templates/node/node--page--card.html.twig
- templates/node/node--page--condensed.html.twig
- templates/node/node--page--list-item.html.twig
- templates/node/node--post--card.html.twig
- templates/node/node--post--condensed.html.twig
- templates/node/node--post--list-item.html.twig
- templates/node/node--profile--card.html.twig
- templates/node/node--profile--condensed.html.twig
- templates/node/node--profile--directory.html.twig
- templates/node/node--profile--list-item.html.twig
- templates/paragraphs/paragraph--custom-card.html.twig
- Adds localist version of the event meta block
- Wires new variables coming from Localist to new event-meta-localist component in the component library
- Adds new library for meta-event-localist - handles content toggles
> YSP-461: Localist: Style Event Meta Block with new designs

- package-lock.json
- package.json
> feat: bump component-library-twig to 1.43.1

- .github/workflows/release.yml
- #230 appears to have broken the release process. Let's restore the previous behavior for now.
> Restore release behavior prior to #230

- package-lock.json
> feat(v140): bump to latest component library twig

- .github/workflows/release.yml
- package-lock.json
> feat(v140): Release

- templates/block/layout-builder/block--inline-block--inline-message.html.twig
- Adds new component for In-Line Message
- Wires new in-line message component
> YSP-335: New block: In-Line Message

- templates/block/layout-builder/block--inline-block--image-banner.html.twig
- Mimics Grand Hero Banner implementation for the image banner
> YSP-641: Image banner block

- package-lock.json
- package.json
- Updates semantic-release to fix secondary rate limit issue during releases
> feat: update semantic-release to ^24

- package-lock.json
- package.json
- Adds functionality bullet item
- Fixes this or that bullet item
> fix(version): bump version to latest in main

- package-lock.json
> fix(component-library-twig): bump to 1.48.0

- atomic.libraries.yml
- templates/layout/region--header.html.twig
- Wiring for new dropdown navigation menu
- Main PR: https://github.com/yalesites-org/yalesites-project/pull/839
> IYY-289: Utility Navigation Dropdown Menu Link Button

- templates/block/layout-builder/block--inline-block--accordion.html.twig
- Wires accordion themes in Drupal
> IYY-294: Accordion Style Variation

- package-lock.json
- Bump CL to 1.50.0 for YaleSites v1.13.x
> Update to CL 1.50.0

- package-lock.json
> Bump CL to 1.51.0

- package-lock.json
> Bump CL to 1.53.0

- package-lock.json
> Bump Component Library to v1.54.0

- package-lock.json
> Bump Component Library Twig to v1.55.0

- templates/block/layout-builder/block--inline-block--grand-hero.html.twig
- Variable for Overlay PNG functionality
> ST-Overlay-PNG

- atomic.libraries.yml
- Applies styling to a table within a section that has a background.
- [Component library twig](https://github.com/yalesites-org/component-library-twig/pull/505)
> IYY-385 :: Table stylign in two columns with a background color

- package-lock.json
> Bump Component Library Twig to v1.56.0

- templates/views/_views-view-search.html.twig
- Adds a tab to see search results across all Yale sites (powered by google programmable search)
See YaleSites PR https://github.com/yalesites-org/yalesites-project/pull/943
> IYY-342: All Yale Results powered by Google Programmable Search

- package-lock.json
> Bump Component Library Twig version to 1.57.0

- package-lock.json
> Hotfix Release

- package-lock.json
> Bump CL to v1.58.0

- package-lock.json
> Bump CL to 1.59.0

- package-lock.json
> Bump component-library-twig to 1.60.0

- package-lock.json
> Bump component library twig to 1.61.0

- css/admin-theme.css
- package-lock.json
- templates/block/layout-builder/block--inline-block--inline-message.html.twig
> Release (RC4)

- package-lock.json
> Bump CL to 1.65.0

- package-lock.json
> Release (RC)
