yalesites-org/atomic

atomic.libraries.yml
templates/layout/region--header.html.twig
templates/ys/ys-alert.html.twig

- Wires the alert block and places it in the header
- Create and attach library for alert JS

YALB-489: Wire Alerts

---

templates/paragraphs/paragraph--pop-out-image.html.twig

- https://github.com/yalesites-org/yalesites-project/pull/15
- https://github.com/yalesites-org/component-library-twig/pull/80
- Wires the Pop-out Image paragraph
- We're not currently providing a caption field. We should figure out how we want to capture that information.

YALB-521: Wire Pop-out Image

---

templates/paragraphs/paragraph--pull-quote.html.twig

- Fixes the attribution variable to no longer display a dash if no content is provided.

YALB-560: removes attribution dash

---

atomic.libraries.yml
atomic.theme
package-lock.json
templates/field/field--field-teaser-title.html.twig
templates/form/container--view.html.twig
templates/form/container.html.twig
templates/node/node--event--card.html.twig
templates/node/node--event--list-item.html.twig
templates/paragraphs/paragraph--event-cards.html.twig
templates/paragraphs/paragraph--event-list.html.twig
templates/views/views-view-unformatted.html.twig
templates/views/views-view.html.twig

- Creates a handful of "default templates" to remove unwanted wrappers added by Stable9
- Wires the card and list view modes for events
- Wires the card and list views for events
- Follow the review steps here: https://github.com/yalesites-org/yalesites-project/pull/59

YALB-495: Wire event paragraphs

---

templates/layout/region--footer.html.twig
templates/layout/region--header.html.twig

- Adds theme settings for header theme, footer theme, and navigation position into twig templates
- **Note**: until YALB-691 is merged in, the "Blue" setting won't work properly.

YALB-237: Add theme settings to twig

---

templates/paragraphs/paragraph--accordion-item.html.twig

- Allows for accordion items to have a dynamic heading level based on the parent accordion heading
- Adds logic for what heading level in ```paragraph--accordion-item.html.twig```
*Note:* These are the same steps as the PR-101 from yalesites-project.

YALB-502: Dynamic accordion heading level

---

templates/node/node--event--full.html.twig

- Fixes the start time bug
- This does not address the "All day" checkbox in Drupal. That wasn't accounted for in design, and we should figure out what that should do on the frontend, or remove the checkbox from the backend.

YALB-718: Fix start time typo

---

package-lock.json
templates/field/field--field-media-oembed-video.html.twig
templates/layout/region--header.html.twig
templates/paragraphs/paragraph--video.html.twig

- Adds the ability to show or hide the search box in the utility navigation area
- Note: This requires [PR-120 from yalesites-project](https://github.com/yalesites-org/yalesites-project/pull/120) and [PR-149 from component-library-twig](https://github.com/yalesites-org/component-library-twig/pull/149) to work

YALB-702: Search: Hide search form

---

templates/form/form-element-label--search-form.html.twig
templates/layout/region--header.html.twig
templates/navigation/menu--utility-navigation.html.twig

- Adds a search form to the utility navigation area
- NOTE: This requires [PR-115](https://github.com/yalesites-org/yalesites-project/pull/115) from yalesites-project and [PR-147](https://github.com/yalesites-org/component-library-twig/pull/147) from component-library-twig

YALB-700: Search Form

---

package-lock.json
templates/field/field--field-author.html.twig
templates/field/field--paragraph--field-media-grid-items--media-grid.html.twig
templates/node/node--news--full.html.twig
templates/paragraphs/paragraph--media-grid.html.twig

- Wires the Image Grid component to Drupal.
- Fixes spacing between the word "By" and the author name on News nodes.

YALB-709: Image Grid Wiring

---

templates/navigation/menu-local-tasks.html.twig

**Bug ticket descriptions**
> The primary tabs (“View”, “Edit”, “Delete”, etc.) `<ul>` wrapper has a semantically incorrect ARIA role  (role="tablist"). This role should be removed.
> Wrap the page tools links (“View”, “Edit”, “Delete”, etc.) in a <nav> tag with an aria-label that describes the purpose of these links, (such as <nav aria-label="page tools">)
- Sets the tabs__component variable to false to prevent the `role="tabslist"` markup from being written
- Wraps the "primary" (drupal) links with a nav and aria-label per the ticket

YALB-784 and YALB-786: Drupal "Primary links" a11y fixes

---

templates/node/node--event--full.html.twig
templates/node/node--full.html.twig
templates/node/node--news--full.html.twig

- updating templates to render the breadcrumb block instead of drupal block layout
- Review with https://github.com/yalesites-org/yalesites-project/pull/158

YALB-405: Feedback: Breadcrumbs

---

templates/paragraphs/paragraph--wrapped-image.html.twig

- Passes the variation controls for the "wrapped image" paragraph.
- This work should be tested in the platform PR
https://github.com/yalesites-org/yalesites-project/pull/189

YALB-877: Wrapped image styles

---

templates/form/ys-search-form.html.twig

- Added padding underneath search page form
- Increases height of text input within search page form
- Before: 
- After:
- Companion PR in component-twig-library: https://github.com/yalesites-org/component-library-twig/pull/185

YALB-913: Bug: Search results page

---

templates/node/node--event--full.html.twig
templates/node/node--news--full.html.twig
templates/paragraphs/paragraph--custom-cards.html.twig
templates/paragraphs/paragraph--gallery.html.twig
templates/paragraphs/paragraph--media-grid.html.twig
templates/paragraphs/paragraph--text.html.twig
templates/views/views-view--event-cards.html.twig
templates/views/views-view--news-cards.html.twig

- passing `width` values in to components to change their widths in Drupal
- setting `page_title__width: 'highlight'` in both the Event and News full templates to reduce the width of page title
- set `media gallery`, `news-cards` and `event-cards` Drupal template includes to `'max'` width

YALB-980: Alignment: Global widths - template updates - wire component library variables

---

templates/views/views-view--views-basic-scaffold.html.twig

- Adds a template for the views basic scaffold view.
- This is be refactored in future work but unblocks us for testing the views basic system.

YALB-944: Define template for views basic

---

templates/views/views-view--search.html.twig

- Fixes bug where search results did not show and instead only showed "placeholder" text.

YALB-1018: Bug: Search results shows placeholder

---

templates/paragraphs/paragraph--text.html.twig

- Set a `text_field__base_class` different to `text-field` in `paragraph--text.html.twig` to send it to the `yds-text-field.twig` file, when the paragraph parent node is `accordion-item` to avoid having an extra margin-bottom in this scenario.

YALB-1051): Fix Accordion spacing

---

templates/views/views-view--event-list.html.twig
templates/views/views-view--news-list.html.twig

This came out of multidev review from the alignment work, here https://dev-yalesites-sebastianna.pantheonsite.io/news-events
The views display is pulling in the non-featured, smaller-image, version of the card list display. 
With these branch fixes,, these displays will change from what you see above, to this, below: 
---
- Updates news and event list displays to use the `featured` display instead of the smaller-image version.

fix(yalb-1104): alignment fix - update featured variable from false to true

---

templates/block/layout-builder/block--inline-block--event-list.html.twig
templates/block/layout-builder/block--inline-block--gallery.html.twig
templates/block/layout-builder/block--inline-block--image.html.twig
templates/block/layout-builder/block--inline-block--media-grid.html.twig
templates/block/layout-builder/block--inline-block--post-list.html.twig
templates/block/layout-builder/block--inline-block--pull-quote.html.twig
templates/block/layout-builder/block--inline-block--tabs.html.twig
templates/block/layout-builder/block--inline-block--text.html.twig
templates/block/layout-builder/block--inline-block--video.html.twig
templates/block/layout-builder/block--inline-block--view.html.twig
templates/block/layout-builder/block--inline-block--wrapped-image.html.twig

- fix(yalb-1141): fix alignment - conditionals in block templates
- adds in conditional width/alignment changes based on parentNode

YALB-1141 - Apply alignment rules to layout builder

---

templates/node/node--event--card.html.twig
templates/node/node--event--list-item.html.twig
templates/node/node--post--card.html.twig
templates/node/node--post--list-item.html.twig

- Adds logic in the twig templates for post and event cards and lists to use the fallback teaser image if a teaser image is not set on the post or event node
- Requires [YaleSites Project PR-263](https://github.com/yalesites-org/yalesites-project/pull/263)
- [Testing multidev here](https://pr-263-yalesites-platform.pantheonsite.io/)

YALB-395: Metadata: Fallback for teaser images (BE)

---

atomic.libraries.yml
templates/block/layout-builder/block--inline-block--button-link.html.twig
templates/block/layout-builder/block--inline-block--grand-hero.html.twig

- YALB-1163 - Adds button-link template
- YALB-1146 - Adds `fontawesome` css as a library - this is a fix because it was not previously added in Drupal. Currently, this only affects the `text-link` component as it's used in the grand hero. I noticed that the text-link in the grand hero was missing its chevron and since I was here I rolled it into 1146.
- YALB-1146 - Fixes grand hero with video play/pause button
- YALB-1146 - Fixes grand hero data attributes - which is this ticket: https://yaleits.atlassian.net/browse/YALB-1146

YALB-1163 - Create Button Link component

---

templates/form/ys-search-form.html.twig

- Adds data attributes to search form to match selected button theme from settings
- Requires [Yalesites Project PR-271](https://github.com/yalesites-org/yalesites-project/pull/271)

YALB-1205: Webform buttons: add preprocess to pass data-cta-theme attribute

---

atomic.info.yml
templates/block/layout-builder/block--inline-block--grand-hero.html.twig
templates/block/layout-builder/block--inline-block--view.html.twig

- Fixes twig syntax issue in two layout builder block templates
-  atomic/templates/block/layout-builder/block--inline-block--view.html.twig 
-  atomic/templates/block/layout-builder/block--inline-block--grand-hero.html.twig
- Fixed based on suggestion here: https://eleni.blog/2019/04/14/upgrading-to-twig-2/
- Adds Drupal 10 compatibility to `atomic.info.yml` file by removing the `core` line and changing `core_version_requirement` to `core_version_requirement: ^9 || ^10`
- While I was in the grand hero template, I swapped the field values in the grand hero, which relates to https://yaleits.atlassian.net/browse/YALB-1146 but doesn't entirely fix that issue. 
- note compatibility :  
https://github.com/yalesites-org/atomic/assets/366413/f17314fd-1492-486e-bc77-61d51ddbe2a7
- While testing …

YALB-1185  - Atomic Drupal 10 Compatibility

---

templates/node/node--event--full.html.twig

This PR is linked to the yalesites-project branch of the same name so that the calendar_link module can be pre-installed and activated.
- Use node object to pass data vs content as layout builder took it over
- Create DateTime representations of the start and end times given
- Use the calendar_link twig function module to create an ics calendar link with some placeholder data
- Create a calculation to determine if 'all day' could have been selected as the 'All day' selection from smart date is not in the node object
- Create a hopefully temporary way of displaying a "label" version of the selected format

YALB-1195: Events: Add to Calendar Link (BE)

---

templates/node/node--page--card.html.twig
templates/node/node--page--list-item.html.twig

- Adds templates for `page--list` and `page--card`

YALB-609: Page lists and grid display modes

---

templates/form/form--views--event-list.html.twig
templates/form/select.html.twig
templates/form/ys-search-form.html.twig
templates/views/views-view--event-list.html.twig
templates/views/views-view--post-list.html.twig

- Adds markup to support ajax filtering for views for Calendar List.
- Main testing instructions here: https://github.com/yalesites-org/yalesites-project/pull/276
- Multidev here: https://pr-276-yalesites-platform.pantheonsite.io/

YALB-1198: Events: Exposed filters on dynamic list (BE)

---

templates/form/form--views--post-list.html.twig
templates/views/views-view--post-list.html.twig

- Adds templates to add exposed filters to post lists
- Note: Incorrectly referenced YALB-1232 in commits, should have been YALB-1230.

YALB-1230: Create Topics vocabulary for Posts

---

templates/ys_embed/broken.html.twig
templates/ys_embed/embed_wrapper.html.twig
templates/ys_embed/instagram.html.twig
templates/ys_embed/powerbi.html.twig
templates/ys_embed/qualtrics.html.twig
templates/ys_embed/soundcloud.html.twig
templates/ys_embed/twitter.html.twig

To be tested in tandem with [Yalesites PR 269](https://github.com/yalesites-org/yalesites-project/pull/269)
- Add new template overload for ys_embed's embed_wrapper to allow embeds to work in pre-configured iframe or legacy inline_templates.

YALB-1197: Media: Allow embed of SoundCloud content (BE)

---

templates/views/views-view--search.html.twig

- Fixes bug where no results text wasn't showing properly.
- No results text will now show if search terms are entered and no results are found.
- New search text will now show if no search terms are entered. (i.e. on /search with no keywords query parameter)
- Requires [PR-320](https://github.com/yalesites-org/yalesites-project/pull/320)

YALB-1288: Bug: Search no results message (BE)

---

templates/paragraphs/_gallery-item.twig

- Fixes error when duplicating gallery item paragraphs
- Main repo is not required for this work, only Atomic.

YALB-1317: Bug: Paragraph duplicate function broken (BE)

---

templates/node/node--event--full.html.twig

- Removes page-title embed in favor of pulling in the `yds-event-meta` with `event_title__heading` mapped to `label` so that the page title renders where it should render instead of causing an empty `h1` accessibility error - and rendering the page title above where it need to be.

YALB-1418: Bug: All events created are showing as past events

---

atomic.theme
templates/node/node--post--full.html.twig

- Changes the visual display of the post date (in cards, lists, and default node view) from the creation date to the date in the "Publish Date" field.
- Also part of [PR-332](https://github.com/yalesites-org/yalesites-project/pull/332)

YALB-1295: Bug: Posts display date of creation and not Publish Date

---

css/admin-theme.css

- Increase size of the contextual button on each component along with the size of the pencil icon
- Move the contextual button from the right-hand side of the screen to the left
- Fixes the appearance of "Move" table item labels on `:hover`
- see video example below
---
- see video example below
---
https://github.com/yalesites-org/atomic/assets/366413/b4ecd236-4bc5-4663-a160-6819a4efa4bb

YALB-1251 - AX: pencil icon difficulty editing blocks | YALB-1261 - Bug: A11y color issue in rollover menu (FE)

---

css/admin-theme.css

- Adds styles to make the secondary-toolbar sticky.

YALB-1419 - OPAC: Move admin toolbar to top

---

templates/layout/html.html.twig

- Adds favicons to site.
- Requires [PR-352](https://github.com/yalesites-org/yalesites-project/pull/352)

YALB-898: Metadata: Add favicon

---

atomic.theme
templates/block/layout-builder/block--inline-block--gallery.html.twig
templates/block/layout-builder/block--inline-block--media-grid.html.twig
templates/block/layout-builder/block--inline-block--video.html.twig
templates/paragraphs/paragraph--accordion-item.html.twig
templates/paragraphs/paragraph--gallery-item--gallery-modal-content.html.twig

This PR is linked to [component-library-twig PR #274](https://github.com/yalesites-org/component-library-twig/pull/274).
The original implementation disregarded the accordion_items in the component library and rendered them in atomic.  This was causing a missing h2 level when no accordion title was present.
To fix this, we preprocess the paragraph__accordion_item to inject a new attribute that will hold the heading_level that should be used, defaulting to 3.
- Add preprocessor for accordion item paragraph to inject the heading level based on the accordion's overall heading presence
- Use the new variable in the paragraph--accordion-item twig file, defaulting to 3 (the original hardcoded value)

YALB-1394: Bug: Accessibility (FE)- Empty heading being inserted when user does not fill in heading field

---

atomic.libraries.yml
css/ckeditor-overrides.css

The modal not working is addressed in [YALB-956](https://yaleits.atlassian.net/browse/YALB-956)
- Add ckeditor-overrides.css file
- Add styling to `.cke_dialog` elements that are more in line with our theme
- No ugly black border lines all over the place
- Attempt to style inputs and selects to match our style in other places
- Style buttons to look like our theme
- Style header to look like our theme
- Recreate X to be a SVG over a black PNG
[YALB-956]: https://yaleits.atlassian.net/browse/YALB-956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YALB-1442: WYSIWYG Creating and editing a table is visually and functionally broken

---

css/layout-builder.css

- Adds quote-specific styles to our Atomic `layout-builder.css` file
- The `p` element isn't part of our design system, so we should include the css here instead of in the component-library
- Test here: https://github.com/yalesites-org/component-library-twig/pull/275

YALB-1407- Bug: Accessibility (FE)- Interactive Media needs roles and tabbing fixes | YALB-1454 - Bug: FE: Quote em dash and name alignment off

---

css/admin-theme.css
templates/block/layout-builder/block--inline-block--button-link.html.twig

- Test here: https://github.com/yalesites-org/yalesites-project/pull/358

YALB-1164 - OPAC: Update admin toolbar icons | 1461 - OPAC: Implement new admin colors and fonts

---

atomic.libraries.yml
templates/navigation/menu--extras--main.html.twig
templates/navigation/menu--main.html.twig

- Attaches the fontawesome library to the main-menu so it is available

YALB 1511 - Theming Primary Navigation Headings

---

css/admin-theme.css

- Adds styling for specific checkbox instances where contrast is an issue (depends on where a checkbox is placed and varies with module use)

YALB-1552: [admin-theme] Update specific checkbox styles for admin-theme areas

---

templates/block/layout-builder/block--inline-block--cta-banner.html.twig
templates/block/layout-builder/block--inline-block--grand-hero.html.twig
templates/block/layout-builder/block--inline-block--view.html.twig

- YALB-1416 - Add check if heading value is present, if so render it, otherwise don't
- YALB-1215 - Wire `heading__level` from each `banner` component to Drupal field `field_heading_level`

fix(yalb-1416): add ternary check for heading value

---

templates/block/layout-builder/block--inline-block--custom-cards.html.twig
templates/block/layout-builder/block--inline-block--directory.html.twig
templates/block/layout-builder/block--inline-block--event-list.html.twig
templates/block/layout-builder/block--inline-block--post-list.html.twig
templates/block/layout-builder/block--inline-block--quick-links.html.twig
templates/paragraphs/paragraph--custom-card.html.twig

- Reverting the application of smart quotes on heading fields as this is causing a problem when these fields are used in components. It is possible we want to change the other text fields in the future. For now, we are keeping the scope small. This change ensure that text (not an object) is passed to the drupal view.
- This is revering work originally committed in this PR https://github.com/yalesites-org/atomic/pull/168/files

YALB-1057: Bug: Smart quotes issue on heading fields

---

atomic.libraries.yml

- Updates fontawesome font paths to load from `/dist` directory of component-library-twig per change in https://github.com/yalesites-org/component-library-twig/pull/295

YALB-1559: Bug: fontawesome fonts included in multidevs but not releases

---

atomic.libraries.yml

> HIGH PRIORITY! Copy button for email link in Profile is not receiving focus and is not tabbable- (should be a button and not a link) @joetower
- Adds a new separate component for copy text link so that we can change the element from an `a` to a `button`. Also, it helps make the text-link component much more lean and makes the new component more purposeful. 
- https://github.com/yalesites-org/component-library-twig/pull/297
- https://github.com/yalesites-org/yalesites-project/pull/433

fix(YALB-email-copy-change-to-button): add new library

---

atomic.libraries.yml
css/admin-theme.css
css/layout-builder.css

Release fixes noted in Teams.
[YALB-1387]: https://yaleits.atlassian.net/browse/YALB-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

September Release Fixes

---

css/admin-theme.css
templates/layout/html.html.twig

- Adds a component for `link skip`: 
- Wires new link skip to `html.html` template.
- Fixes chosen input search colors on `admin/content` tags

YALB-1527 - Bug: Update link styling "Skip to Main Content" | YALB-1560 - Blank space in toolbar on admin theme

---

templates/block/layout-builder/block--inline-block--text.html.twig

- Adds variation option to the `text` component for `emphasized`
- Themes the emphasized variation to use the body-xl style: https://yalesites-org.github.io/component-library-twig/?path=/story/tokens-typography--body-styles
- Note branched PRs in Atomic and Component library:
- https://github.com/yalesites-org/atomic/pull/191
- https://github.com/yalesites-org/component-library-twig/pull/315

YALB-1306: Emphasized text - Wiring

---

css/layout-builder.css

- Adds `margin-top: auto` to the layout-builder.css file to make the footer "hug" the bottom of the browser window
- This issue was caused by `site-footer` being wrapped in a new `div` `#block-yalesitesfooterblock`

YALB-1624 - Bug: Footer placement off when short page has visually hidden title

---

templates/node/node--profile--card.html.twig
templates/node/node--profile--directory.html.twig
templates/node/node--profile--list-item.html.twig

- Adds a fallback image if someone doesn't add a profile image or a teaser image to a profile node.

YALB-1661: Profile media image being used for page and view block

---

css/layout-builder.css
templates/block/layout-builder/_layout-builder-block-template.twig
templates/block/layout-builder/block--broken.html.twig

- Adds custom styles now that we've removed wingsuit

YALB-1650 - Reusable Content: Browser UX

---

atomic.libraries.yml

MultiDev PR: https://github.com/yalesites-org/yalesites-project/pull/467
Component Library PR: https://github.com/yalesites-org/component-library-twig/pull/319
Atomic PR: https://github.com/yalesites-org/atomic/compare/YALB-520-links-dynamically-apply-link-treatments
- Adds javascript sprinkles to identify and modify links on page to match component-library-twig links
- Links decorated:
- External
- Downloads
- Target Blank

YALB-520: Links: Dynamically apply link treatments

---

templates/node/node--event--card.html.twig
templates/node/node--event--condensed.html.twig
templates/node/node--event--list-item.html.twig
templates/node/node--search-result.html.twig

- Wires new field_external_source to URL if available, otherwise it sets `url` to `url`.

YALB-680: Links: Link to external content in lists of cards 

---

atomic.libraries.yml
css/layout-builder.css
templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
templates/block/layout-builder/block--inline-block--content-spotlight.html.twig

- Adds new library for spotlight component JS
- Attaches the library to the two spotlight component block templates

 YALB-1697: Bug: Margin for spotlights

---

templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
templates/block/layout-builder/block--inline-block--custom-cards.html.twig

- Wire the heading and subheading field for conditional logic

YSP-277: Spotlight without header shows an empty h tag

---

templates/node/node--profile--directory.html.twig

- Wires `directory_listing_card_link__url` to `'mailto:' ~ content.field_email[0]['#context'].value|trim|lower`

YSP-275: Long email breaks Profile card grid: update wired variables

---

templates/paragraphs/_gallery-item.twig
templates/paragraphs/paragraph--gallery-item--gallery-modal-media.html.twig

When troubleshooting a different issue, we found an issue where when an image that's used in a gallery is deleted, it resulted in a page error from TwigTweak.
This checks against this deletion and conveys to the user that the image is missing should it be deleted.
Work was also done in [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/344)
- Add guard against loading a media that does not exist
- If the media does not exist, render component library's image with empty params for "Missing image" message.
OR

YSP-375: TwigTweak errors when removing media used in gallery

---

templates/node/node--event--card.html.twig

- Adds conditional logic to `reference__card__overline` in Atomic template: 
- Adds `bottom-margin` to `__image` s in card grid to create more space between the image and the heading

YSP-366: Card display mode spacing between heading, content, and image

---

css/admin-theme.css

- Disables animation on "throbber"
- Displays the throbber in front of the edit/delete links that usually appear on the image

YSP-415: Add media text spinning

---

css/admin-theme.css

- Change CSS to use `--gin-color-text` where found.

YSP-422: AX headings aren't adapting to light/dark mode

---

templates/block/layout-builder/block--inline-block--cta-banner.html.twig
templates/block/layout-builder/block--inline-block--grand-hero.html.twig

- Adds optional second link field for cta banner and grand hero banner
- Adds a button-group wrapping div to preserve the existing space between elements
- Adds wiring for optional second link

YSP-430: Canvas user need to allow two call to actions in banner

---

templates/block/layout-builder/block--inline-block--reference-card.html.twig
templates/field/field--block-content--field-content-ref--reference-card.html.twig
templates/node/node--event--single.html.twig
templates/node/node--post--single.html.twig
templates/node/node--profile--single.html.twig

**Relates to**
- Adds templates that connect the BE to the FE for the reference card component
- Related to [this PR](https://github.com/yalesites-org/yalesites-project/pull/616) in Yalesites Project and [this PR](https://github.com/yalesites-org/component-library-twig/pull/345) in the component library
-

YSP-436: Reference cards: Backend and content tools

---

atomic.libraries.yml
css/localist.css

The shadow set for the button was set to the text color instead of what the current background color was, resulting in a hard to read button text.  Due to localist defining the color of the button, we copied this value from them in order to make it look correct.
The other links have our animation effect, however localist was defining a hover line to appear, which made this look awful.  This forces the links to not underline and to instead use our underline effect.
- Add `localist.css` file to break up concerns
- Change shadow color to match background sent from localist styling
- Force override of localist hover underline so we can have our animations

YSP-399: Localist: Embedding widgets

---

.github/workflows/release.yml

- Updates actions/checkout, actions/setup-node, EndBug/add-and-commit to latest versions
- Since node 16 is now deprecated in github actions, run setup-node with node 20

Update all actions to latest and run setup-node with node 20

---

css/admin-theme.css

- Adds styling for the new moderation sidebar
- Adds styling for the moderation form when nodes are in a draft state

YSP-458: Editorial Workflow: Display improvements to right panel

---

templates/ys_embed/embed_wrapper.html.twig

- [YaleSites Project: PR #676](https://github.com/yalesites-org/yalesites-project/pull/676)
- [Component Library Twig: PR #376](https://github.com/yalesites-org/component-library-twig/pull/376)
- Wires up allowfullscreen to embeds

YSP-487: Add JWPlayer Embed

---

templates/layout/region--header.html.twig

- Hide the hamburger icon when all the menus are empty.
- Adds `site_header__hamburger` as a variable conditionally set by either `utility_nav__items` or `primary_nav__items` having items within them
- In Atomic, `utility_nav__items` or `primary_nav__items` are set to
```
{% set primary_nav__items = elements.main_navigation.content['#items'] %}
{% set utility_nav__items = elements.utility_navigation.content['#items'] %}
```

YSP-554 - Hamburger icon shows on empty menu

---

.github/workflows/release.yml
package.json

`main` and `develop` branches are out of sync due to the changes committed to `main` during releases. This PR proposes these changes:
- Instead of making 2 commits - one to add the component library, and one to delete it - do a `git reset` to `$GITHUB_SHA`, which is the SHA that triggered the build, instead of making a second commit. This prevents main from getting out of sync just to package the build assets
- Switch the commit author to Github Actions bot
- Unrelated cleanup: remove the custom `npm semantic-release` command and run semantic-release with npx

Reset main branch when creating releases

---

package-lock.json
package.json

This is an attempt to make semantic release not reuse the same version tag it had before.  I'm hoping I just forgot to perform this step.

fix(semrel): update version to help semrel

---

README.md
templates/layout/region--header.html.twig

More work done in [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/389) for this.
- Reverts the conditional logic to not display the hamburger
- Remember that the real issue cannot be duplicated on multidevs or locally, but the reverted code ensures display in every case.

YSP-581: Mobile hamburger menu not showing up

---

templates/layout/region--header.html.twig

This allows the transfer of the branding name and URL settings to the rendering of the secondary header.  This enables a customization of the branding that is shown sitewide, along with the URL it links to.
[Yalesites Project](https://github.com/yalesites-org/yalesites-project/pull/711)
[Atomic](https://github.com/yalesites-org/atomic/pull/255)
[Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/391)
- Passes sitewide branding name and link URL to component library twig

YSP-495: Site-wide branding for University groups

---

templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
templates/layout/region--header.html.twig

Previously, "Spotlight Cards" supported only one Call-to-Action (CTA) link. This pull request enhances the functionality by allowing a second CTA link to be added and rendered on the cards.
- Add field_link_two data in the Content Spotlight block templates
Related PRs:
- https://github.com/yalesites-org/yalesites-project/pull/729
- https://github.com/yalesites-org/component-library-twig/pull/396

JAKALA: Spotlight cards enhancement

---

templates/form/ys-search-form.html.twig
templates/node/node--search-result.html.twig

The scope of this task is to add a new filter on the search page and style it based on the updated design.
- Render content type filter dropdown in the search form on the search page.
- Adjust form markup to include proper form item labels.
Related PRs:
- https://github.com/yalesites-org/yalesites-project/pull/727
- https://github.com/yalesites-org/component-library-twig/pull/398

JAKALA: Add Content Type filter to Search Page

---

templates/block/layout-builder/block--inline-block--video.html.twig

- Wires the video alignment to the video component

YSP-662: PRESIDENT: allow center or larger view of video block

---

css/layout-builder.css
templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
templates/block/layout-builder/block--inline-block--content-spotlight.html.twig

- Passes `field_heading_level` through to components for spotlights
Please test in yalesites project PR.

YSP-670: Spotlights provide H2 in Banner Section

---

css/layout-builder.css
templates/block/layout-builder/block--inline-block--image-banner.html.twig

- [YaleSites Project](https://github.com/yalesites-org/yalesites-project/pull/770)
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/423)
- Adds image banner size dial to image banner (large or small)
- Mimics the grand hero layout and styling to have consistent feel

YSP-680: PRESIDENT: Add dial to image banner to allow default and large image display

---

templates/field/field--block-content--field-media--image-banner.html.twig

The div that is inserted for the item seems to be modifying how the image banner behaves, skipping the styling of it to match the grand hero.  By creating this, it allows it to bypass this, picking up the styles similar to the grand hero in Drupal.
- Adds a bypass to the item content so that the extra unsettled div does not get rendered

YSP-697: Image Banner not respecting focal point

---

css/admin-theme.css
css/layout-builder.css

Work reflected in the [Yalesites project PR](https://github.com/yalesites-org/yalesites-project/pull/793)
- Remove left and right margins on content when in layout builder
- Hide empty blocks shown when filtering blocks in the picker
- Fix accordion colors on text-within
- Fix hover/focus contrast on linkit
- Fix vertical ellipsis menu from allowing items underneath to show
- Remove strange gradient on collapsed paragraphs

v1.10.0: Multiple fixes

---

templates/block/layout-builder/block--inline-block--wrapped-text-callout.html.twig

- Wires up the new wrapped text callout component

IYY-282: Site Editors can add a simple outlined callout

---

templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
templates/block/layout-builder/block--inline-block--content-spotlight.html.twig

- Wires vertical alignment options to Content Spotlight Portrait
- Wires vertical alignment options to Content Spotlight Landscape
- CL: https://github.com/yalesites-org/component-library-twig/pull/452

IYY-302: Add vertical text alignment to Spotlights

---

css/admin-theme.css
css/layout-builder.css
templates/block/layout-builder/block--inline-block--facts.html.twig
templates/block/layout-builder/block--inline-block--link-grid.html.twig
templates/block/layout-builder/block--inline-block--tiles.html.twig
templates/layouts/layout--onecol.html.twig

- Adds a twig variable to layout builder components of the current layout section to better style based on context
- Requires [Main Repo PR-826](https://github.com/yalesites-org/yalesites-project/pull/826) and [Component Library Twig PR-442](https://github.com/yalesites-org/component-library-twig/pull/442)

IYY-283: Site editors can create a ½ - ½ layout and ⅓ - ⅓ - ⅓ layout

---

atomic.libraries.yml
templates/form/form-element-label--ys-themes-settings-form--book-navigation.html.twig
templates/navigation/book-tree.html.twig
templates/node/node--full.html.twig

- Adds dynamic theming for the book navigation

IYY-287: Install and enable Drupal Book module

---

templates/block/layout-builder/block--inline-block--video-banner.html.twig

- Wires new Video Banner to its block type
- YaleSites Platform: https://github.com/yalesites-org/yalesites-project/pull/863
- Component Library: https://github.com/yalesites-org/component-library-twig/pull/466

IYY-327: Support Video Embed on Image Banner

---

templates/node/node--event--card.html.twig
templates/node/node--event--condensed.html.twig
templates/node/node--event--list-item.html.twig
templates/node/node--event--single.html.twig
templates/node/node--page--card.html.twig
templates/node/node--page--condensed.html.twig
templates/node/node--page--list-item.html.twig
templates/node/node--post--card.html.twig
templates/node/node--post--condensed.html.twig
templates/node/node--post--list-item.html.twig
templates/node/node--post--single.html.twig
templates/node/node--profile--card.html.twig
templates/node/node--profile--condensed.html.twig
templates/node/node--profile--list-item.html.twig
templates/node/node--profile--single.html.twig

This work is dependent on the following other PRs--please review these as well:
- [YaleSites Project](https://github.com/yalesites-org/yalesites-project/pull/860)
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/462)
- Added `reference_card__overlay` to include pin label in the card.
- Included conditional block to render pin label if it exists.
- Updated `yds-text.twig` to display the pin label as an overlay.

YSP-769: Add "Pin to Top" visual indicator

---

css/layout-builder.css
templates/block/layout-builder/block--inline-block--image-banner.html.twig

- Wires Image Banner Caption
- Component Library: https://github.com/yalesites-org/component-library-twig/pull/450
- YaleSites Platform: https://github.com/yalesites-org/yalesites-project/pull/833

IYY-285: Site editors can add a caption to Image Banner | Wiring

---

templates/block/block--custom-book-navigation.html.twig

- Prevents the ability to click on the collection links in the collection navigation while in layout builder.

IYY-335: Follow-ups on Book Module/Secondary Nav

---

css/layout-builder.css

- Overload CKEditor's width settings on paragraph-based actions

YSP-574: Paragraph blocks - items 3 dot menu option not showing properly

---

templates/layout/region--header.html.twig

- Hides the hamburger menu if there are no items in the main and utility menus.
- [  ] Delete or disable all menu items in both menus, verify you cannot see the hamburger menu
- [  ] Enable at least one menu item in either menu, verify you can see the hamburger menu.

YSP-738 :: Reimplement hiding hamburger menu if no menu items exist

---

templates/node/node--event--card.html.twig
templates/node/node--event--condensed.html.twig
templates/node/node--event--list-item.html.twig
templates/node/node--event--single.html.twig

- Introduced delta variable to handle multiple event dates.
- Updated templates to use delta for rendering event start times.
- Ensured backward compatibility by defaulting delta to 0.

YSP-844: Event Meta Block Date Visibility Improvements

---

templates/node/node--post--list-item.html.twig

- Tabs: Transparent tab buttons on dark backgrounds and improved text contrast.
- Pre-built Forms: Adjusted input background colors and fixed asterisk color for visibility.
- Quote: Dynamically adjusted text color based on section background.
- Divider: Updated color to adapt to section background.
- Button: Colors adjusted for proper contrast with section backgrounds.
- Accordion: Applied color adjustments similar to tabs.
- Reference Card: Repositioned text area for better text width and layout.
- [YaleSites Project](https://github.com/yalesites-org/yalesites-project/pull/898)
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/490)

 YSP-761 :: Add available blocks to regions for new layouts #490 

---

templates/node/node--page--single.html.twig

- [Yalesites Project](https://github.com/yalesites-org/yalesites-project/pull/934)
- Introduce a new Twig template for single page nodes. This template embeds the reference card component and dynamically sets its properties such as heading, URL, snippet, and eyebrow. It also handles fallback logic for teaser media images.
- See [YaleSites Project PR for steps](https://github.com/yalesites-org/yalesites-project/pull/934)

YSP-589: Add Page Content Type Support to Reference Card Block

---

css/layout-builder.css

- Added a CSS rule to reset the margin-bottom of the last child inside nested divs within `.main-content .layout--banner .layout__region`. This ensures consistent spacing and prevents unnecessary gaps.

YSP-803: Reduce Excessive Padding Between Breadcrumbs and Banner Blocks

---

templates/block/layout-builder/block--inline-block--webform.html.twig

- [Yalesites Project](https://github.com/yalesites-org/yalesites-project/pull/936)
- Include an inline message for configuration issues in the webform block template. This message displays when the `#configuration_issue` key is present in the content array. The message uses the `yds-inline-message` component with a heading, content, type, and theme for better user feedback.

YSP-880: Change default site email from noreply@yale.edu to noreply@noreply.yale.edu

---

css/layout-builder.css

- [Multidev PR](https://github.com/yalesites-org/yalesites-project/pull/952)
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/506)
- Removed unnecessary dark mode table hover and focus-within styles that caused incorrect text rendering.

YSP-875: Text: Tables in a section have a color contrast issue

---

css/layout-builder.css

- Added a CSS rule to enhance the contrast of weight links in dark mode by setting their color to `var(--gin-color-text)`. This ensures better readability and accessibility for users in dark mode.

YSP-928: Layout Builder Block Tables in Dark Mode Unreadable

---

templates/navigation/ys-breadcrumb-block.html.twig

- Removed the explicit passing of `breadcrumbs__trail_level` variable from the breadcrumb block template include, as it is no longer needed. 
- Work also done in [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/524)
- See [Yalesites PR multidev](https://github.com/yalesites-org/yalesites-project/pull/985)

Hotfix: YSP-951: Breadcrumbs not showing more than 2 trails levels

---

css/ckeditor5.css
css/layout-builder.css

- Override global table styles for tables inside layout builder dialog boxes in dark mode.
- Work also done in [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/520) and [Yalesites Project](https://github.com/yalesites-org/yalesites-project/pull/980)

Hotfix: YSP-943/YSP-945: Grand Hero and Table fixes

---

templates/node/node--event--card.html.twig
templates/node/node--event--list-item.html.twig
templates/node/node--page--card.html.twig
templates/node/node--page--list-item.html.twig
templates/node/node--post--card.html.twig
templates/node/node--post--list-item.html.twig
templates/node/node--profile--card.html.twig
templates/node/node--profile--list-item.html.twig

- Changes the reference_card__image property (which corresponds to 'withImage' in js files) to be set using the show_thumbnails property from ys_views_basic so that the show_thumbnail is no longer required in the component. 
Note: In the twig file, there were two properties being set to control the image display: reference_card__image and show_thumbnail. I have updated it so that it only uses reference_card__image which is set by 'Show Teaser Image' or 'withImage' if in Storybook, and is by default set to 'true' (the canonical node, Featured Card block).
Uses component library branch: https://github.com/yalesites-org/component-library-twig/pull/493

YSP-814:: Remove `Show Thumbnails` in reference card to use `with-image`

---

atomic.info.yml
atomic.libraries.yml
js/disable-menu.js
templates/layout/region--header.html.twig

- Add a new library and JS behavior to hide the hamburger menu button when both utility and primary navigation items are absent.
- Updates `atomic.info.yml` and `atomic.libraries.yml` to register the new script.

YSP-738: Hide hamburger menu if no nav items exist

---

templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
templates/block/layout-builder/block--inline-block--content-spotlight.html.twig

- Adjusts templates for spotlight blocks to include caption
Uses platform branch: https://github.com/yalesites-org/yalesites-project/pull/1008
Uses CL branch: https://github.com/yalesites-org/component-library-twig/pull/532

YSP-948 :: Add Caption Field to Spotlight Blocks (Landscape and Portrait)

---

atomic.theme
css/admin-theme.css

- Implement hook_preprocess_pager() in atomic.theme to add the total number of pages to the pager variables.
- Work also completed in [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/528) and [Yalesites Project](https://github.com/yalesites-org/yalesites-project/pull/995)

YSP-568: Improve pagination - too many options

---

templates/paragraphs/paragraph--facts-item.html.twig

- Update Facts and Figures twig template to render icons
- Other work completed in:
- https://github.com/yalesites-org/yalesites-project/pull/1012
- https://github.com/yalesites-org/component-library-twig/pull/533

YSP-928: Facts and Figures Block - Add Icon Selection Feature

---

atomic.theme
css/layout-builder.css
templates/views/views-view--views-basic-scaffold-events.html.twig
templates/views/views-view--views-basic-scaffold.html.twig

- Adds the ARIA role "group" to the inline block view template for improved accessibility.
- Hide pencil icon for custom collection navigation section

YSP-1069: Pagination View A11y Changes

---

css/layout-builder.css

- Remove top padding from spotlights in banner region.
Demo: https://pr-1073-yalesites-platform.pantheonsite.io/spotlight-in-banner-region-test

YSP-936 :: Remove Extra Top Padding from Spotlight Blocks in Banner Regions
